### ISSUE TITLE
How to simulate combats with SparCraft? What is the operational process?Thank you very much! 

### ISSUE THREAD

**Issue by wanglin95** [levilelis/Sparcraft#1]
I want to assign units to both sides of the battle and then get the winning rate. But I don't know how to do it. What is the configfile that needs to be entered in the SparCraft_main project? Need to write it by myself? Could you please introduce me the operational process of the simulation? Thank you so much！

**Comment by levilelis** [comment]
Take a look at the configuration file Sparcraft/sample_experiment/sample_exp.txt.

In that file you are able to configure which AI will play against another and the kind of initial states will be used (search for 'State SeparatedState' in that file).

**Comment by wanglin95** [comment]
State SeparatedState 100 128 128 400 360 840 360 Protoss_Dragoon 5 Protoss_Zealot 12
State SeparatedState 100 128 128 400 360 840 360 Protoss_Dark_Templar 15
Does each line represent a player's units?The first line is for player 1, the second line is for player 2, right? I do not quite understand.

**Comment by wanglin95** [comment]
In the configuration of SeparatedState, how to specify the units for Player 1 and Player 2 respectively？

**Comment by levilelis** [comment]
The units you specify are for both players: the number and type of units will be the same for both players. 

I am afraid you will have to write code if you wish to run experiments with players controlling armies of different sizes.

**Comment by wanglin95** [comment]
OK, Thank you!

**Comment by wanglin95** [comment]
In the configuration of StateDescriptionFile , we can specify different numbers of units for Player 1 and Player 2 respectively. Can I use this configuration  to experiment directly?

**Comment by levilelis** [comment]
There you go - you already know more than I do!

**Comment by wanglin95** [comment]
I mean, can I use StateDescriptionFile to do experiment? Most of the articles I read are configured with SeparatedState.

**Comment by levilelis** [comment]
It really depends on your research question. For the work I did I chose to use states with exactly the same number of units on each side. You could be interested in something different though. For example, if you are trying to show that you have an algorithm that is able to win even if controlling a smaller number of units, then your experiment makes sense to me.

**Comment by wanglin95** [comment]
System::FatalError("Move Action with distance 0 generated")
When using some units, this error will occur, how to deal with it?
